### ISSUE TITLE
Optimize Image Size

### ISSUE THREAD

**Issue by ErdemOzgen** [ErdemOzgen/blackcart#13]

**Comment by KBErdogdu** [comment]
Hey, using [docker-squash ](https://github.com/goldmann/docker-squash)helped me to reduce image size. 

- [ ] Install docker-squash

- [ ]  run this command: docker-squash -t your-optimized-image:tag **your-existing-image:tag**

**Comment by ErdemOzgen** [comment]
I will try to add in github actions
