### ISSUE TITLE
Install puredns

### ISSUE THREAD

**Issue by ataseren** [ErdemOzgen/blackcart#27]
puredns is needed for some YAMLs to work. It will also be a good addition to the arsenal for future YAMLs.

It can be installed with `install puredns` command in BlackArch Linux.

**Comment by ErdemOzgen** [comment]
I will be update tonight

**Comment by ataseren** [comment]
I found that puredns requires a list of resolvers to work. Here is a repository that keeps up-to-date resolvers: https://github.com/trickest/resolvers
