### ISSUE TITLE
Install page-fetch

### ISSUE THREAD

**Issue by ataseren** [ErdemOzgen/blackcart#30]
For some of the YAMLs, page-fetch tool is required. It can be installed with `go install github.com/detectify/page-fetch@latest`.

**Comment by ErdemOzgen** [comment]
(blackcartenv) [ 2bea0fdd7721 /work_dir ]# page-fetch 
error starting browser: exec: "google-chrome": executable file not found in $PATH

Using in black cart not supported right now.
